name: Build Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  Library-ModelCompositionRefinement:
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.4
    with:
      use-display-output: true
      runner-label: ubuntu-latest
      deploy-updatesite: 'releng/tools.mdsd.mocore.updatesite/target/repository'
    secrets:
      SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
      REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
      REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
      REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
