# This workflow will verify a Java 11 project with Maven
name: Maven Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '4 2 * * 0' # once a week, Sundays at 02:04 UTC.
  workflow_dispatch: # manual trigger

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run Maven
      run: mvn -B -U clean verify
